// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsSxKt5SkAOv5BztAY_uZvZpAUImrjNs',
    appId: '1:655664352175:web:58c1fe578cea8283f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    authDomain: 'mathkiddo-loginpage.firebaseapp.com',
    storageBucket: 'mathkiddo-loginpage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdQM9kQ7VwBGO_bUKA73HE2ZOQDmNZm0',
    appId: '1:655664352175:android:34549184e45a8ef7f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzH3fT9nqOY-2hExJWo8kfGgwLFTcfclE',
    appId: '1:655664352175:ios:671b925acc131f60f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.firebasestorage.app',
    iosBundleId: 'com.example.mathkiddo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzH3fT9nqOY-2hExJWo8kfGgwLFTcfclE',
    appId: '1:655664352175:ios:671b925acc131f60f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.firebasestorage.app',
    iosBundleId: 'com.example.mathkiddo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Prr3rhqkIn-6nA2n8ssjuFLNIONxQwg',
    appId: '1:655664352175:web:0276093695582afcf3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    authDomain: 'mathkiddo-loginpage.firebaseapp.com',
    storageBucket: 'mathkiddo-loginpage.firebasestorage.app',
  );

}