// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsSxKt5SkAOv5BztAY_uZvZpAUImrjNs',
    appId: '1:655664352175:web:58c1fe578cea8283f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    authDomain: 'mathkiddo-loginpage.firebaseapp.com',
    storageBucket: 'mathkiddo-loginpage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdQM9kQ7VwBGO_bUKA73HE2ZOQDmNZm0',
    appId: '1:655664352175:android:28c447591036af88f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzH3fT9nqOY-2hExJWo8kfGgwLFTcfclE',
    appId: '1:655664352175:ios:6701324beaafc2a4f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzH3fT9nqOY-2hExJWo8kfGgwLFTcfclE',
    appId: '1:655664352175:ios:6fc4392973449875f3bd5a',
    messagingSenderId: '655664352175',
    projectId: 'mathkiddo-loginpage',
    storageBucket: 'mathkiddo-loginpage.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
